# Generated by Django 4.2.5 on 2024-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admissoon_date',
            field=models.DateTimeField(),
        ),
    ]
